name: Build Common Model

env:
  project: common.model  
  major: 1
  minor: 0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  set-version:
    uses: ${{ github.repository_owner }}/Common.Tools/.github/workflows/BuildVersion.yml@main
    with:
      major: ${{ env.major }}
      minor: ${{ env.minor }}

  build-nuget-package:
    needs: set-version
    uses: ${{ github.repository_owner }}/Common.Tools/.github/workflows/BuildNuget.yml@main
    with:
      project: ${{ env.project }}
      version: ${{ jobs.set-version.outputs.build-version }}
    secrets: inherit
