name: Build Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  set-version:
    uses: NivagL/Common.Tools/.github/workflows/build-version.yml@main
    with:
      major: 1
      minor: 0

  build-nuget-package:
    needs: set-version
    uses: NivagL/Common.Tools/.github/workflows/build-model-nuget.yml@main
    with:
      project: 'common.model'
      version: ${{ needs.set-version.outputs['build-version'] }}
    secrets: inherit

  build-npm-package:
    needs: [set-version, build-nuget-package]
    uses: NivagL/Common.Tools/.github/workflows/build-model-npm.yml@main
    with:
      project: 'common.model'
      version: ${{ needs.set-version.outputs['build-version'] }}
    secrets: inherit

