name: Build Common Model

env:
  project: common.model  
  major: 1
  minor: 0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-model:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.build-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        id: set-version
        uses: Common.Tools/Pipeline/Build/BuildVersion.yml@main
        with:
          major: ${{ env.major }}
          minor: ${{ env.minor }}

      - name: Build nuget package
        uses: Common.Tools/Pipeline/Build/BuildNuget.yml@main
        with:
          project: ${{ env.project }}
          version: ${{ steps.set-version.outputs.build-version }}
        env:
          GH_PACKAGES: ${{ secrets.GH_PACKAGES }}
